import { DevtoolsProvider } from "@/providers/devtools";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";

import { authProviderClient } from "@/providers/auth-provider/auth-provider.client";
import { dataProvider } from "@/providers/data-provider";
import { liveProvider } from "@/providers/live-provider";
import "@/styles/global.css";
import { accessControlProvider } from "@/providers/access-provider/access-control-provider";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Suspense>
          <RefineKbarProvider>
            <DevtoolsProvider>
              <Refine
                routerProvider={routerProvider}
                authProvider={authProviderClient}
                dataProvider={dataProvider}
                liveProvider={ liveProvider}
                accessControlProvider={accessControlProvider}
                resources={[
                  {
                    name: "companies",
                    list: "/dashboard",
                    show: "/dashboard/company/:id",
                    meta: {
                      canDelete: true,
                      dataProviderName: "companies",
                    },
                  },
                  {
                    name: "certificates",
                    list: "/dashboard",
                    show: "/dashboard/certificate/:id",
                    meta: {
                      canDelete: true,
                      dataProviderName: "certificates",
                    },
                  },
              
                ]}
                options={{
                  liveMode: "manual",
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "gOQzeh-nNSFNH-LlTyAF",
                }}
              >
               {children}
                <RefineKbar />
              </Refine>
            </DevtoolsProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
